const FETCH_FILMS = 'FETCH_FILMS';
const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST';
const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
const FETCH_FILMS_FAILED = 'FETCH_FILMS_FAILED';

const FETCH_FILM = 'FETCH_FILM';
const FETCH_FILM_REQUEST = 'FETCH_FILM_REQUEST';
const FETCH_FILM_SUCCESS = 'FETCH_FILM_SUCCESS';
const FETCH_FILM_FAILED = 'FETCH_FILM_FAILED';

const CREATE_FILM = 'CREATE_FILM';
const CREATE_FILM_REQUEST = 'CREATE_FILM_REQUEST';
const CREATE_FILM_SUCCESS = 'CREATE_FILM_SUCCESS';
const CREATE_FILM_FAILED = 'CREATE_FILM_FAILED';

const EDIT_FILM = 'EDIT_FILM';
const EDIT_FILM_REQUEST = 'EDIT_FILM_REQUEST';
const EDIT_FILM_SUCCESS = 'EDIT_FILM_SUCCESS';
const EDIT_FILM_FAILED = 'EDIT_FILM_FAILED';

const DELETE_FILM = 'DELETE_FILM';
const DELETE_FILM_REQUEST = 'DELETE_FILM_REQUEST';
const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
const DELETE_FILM_FAILED = 'DELETE_FILM_FAILED';

export {
  FETCH_FILMS,
  FETCH_FILMS_REQUEST,
  FETCH_FILMS_SUCCESS,
  FETCH_FILMS_FAILED,
  FETCH_FILM,
  FETCH_FILM_REQUEST,
  FETCH_FILM_SUCCESS,
  FETCH_FILM_FAILED,
  CREATE_FILM,
  CREATE_FILM_REQUEST,
  CREATE_FILM_SUCCESS,
  CREATE_FILM_FAILED,
  EDIT_FILM,
  EDIT_FILM_REQUEST,
  EDIT_FILM_SUCCESS,
  EDIT_FILM_FAILED,
  DELETE_FILM,
  DELETE_FILM_REQUEST,
  DELETE_FILM_SUCCESS,
  DELETE_FILM_FAILED
};
